### ISSUE TITLE
random segfault

### ISSUE THREAD

**Issue by ghost** [rust-lang/measureme#210]
I tried to use self profile and summarize seems to segfault.

Steps to reproduce:
- Download and install the latest nightly toolchain
- Set the toolchain to default
- run `RUSTFLAGS="-Zself-profile" cargo build`
- try to use `summarize summarize <filename>`

Result:
`zsh: segmentation fault (core dumped)  summarize summarize ...`

## Additional info
I'm working in a cargo workspace where each member contains a binary and a library
some contain two binaries.

## System Info
```
rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.74.0-nightly (c469197b1 2023-08-22)`
```

ArchLinux, kernel 6.4.11-arch2-1

**Comment by andjo403** [comment]
more information is needed is the crate that you get the fault with available some where or can you print the backtrace from the coredump?

**Comment by bjorn3** [comment]
Which version of summarize are you using?

**Comment by tgnottingham** [comment]
I see segfaults when running summarize in release mode off of the stable branch / 10.0.0 tag (6129647e1727be1f9855f0158be4a0a538298514), which is what you get when installing as laid out in the README (`cargo install --git https://github.com/rust-lang/measureme --branch stable summarize`).

The segfault doesn't happen when built with the dev profile on the stable branch, nor when built with the release profile on the master branch. Git bisecting shows that it was fixed by https://github.com/rust-lang/measureme/pull/202.

**Comment by lazear** [comment]
I am having the same issue - on both a private project, but also a [public one](https://github.com/lazear/sage).
```
$ cargo install --git https://github.com/rust-lang/measureme --branch stable summarize
$ RUSTFLAGS="-Zself-profile" cargo +"nightly-2023-06-15-aarch64-apple-darwin" build
$ summarize summarize sage-0029664.mm_profdata
> zsh: segmentation fault  summarize summarize sage-0029664.mm_profdata
```

`Darwin Michaels-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; arm64`

**Comment by Zannick** [comment]
Stable is now 2 years since its last update, and I just encountered this problem myself. Please update stable or update the docs.

**Comment by michaelwoerister** [comment]
The stable branch is up-to-date now. We'll look into a way for better taking care of this in the future.
