### ISSUE TITLE
panic! when analyzing profiler events

### ISSUE THREAD

**Issue by lokalmatador** [rust-lang/measureme#48]
I dumped some profiler events using `-Z self-profile` running rustc with an own stage2 build (1.36.0-dev on ubuntu 18.04). I also used that one to compile measureme (0.3.0-4-gbb14545). Running `./summarize pid-{pid}` yields

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"GenericActivity"`,
 right: `"Query"`', summarize/src/analysis.rs:150:17
```

[Attached](https://github.com/rust-lang/measureme/files/3214264/profiler_events.zip) are two sets of profiler events that produce the error.

**Comment by wesleywiser** [comment]
Ok, so it looks like the issue is with these two events from your file:

```
Event { event_kind: "GenericActivity", label: "polonius:solve", additional_data: [], timestamp: SystemTime { tv_sec: 0, tv_nsec: 52529740 }, timestamp_kind: Start, thread_id: 2 }
Event { event_kind: "Query", label: "mir_borrowck", additional_data: [], timestamp: SystemTime { tv_sec: 0, tv_nsec: 52624559 }, timestamp_kind: End, thread_id: 2 }
```

You can think of Start/End events as forming a kind of stack. When a Start event occurs, a new frame is pushed onto the stack and when an End event occurs, that frame is popped from the stack. 

What's happened here is that we've pushed a new frame for the `polonius::solve` event but then we're asked to pop the `mir_borrowck` event which isn't the top frame on the stack. That's not allowed. 

I've looked through the rest of the file and I don't see any Ends for `polonius::*` events so I think the issue is just that you're missing a call to end the activity at the appropriate place.

**Comment by michaelwoerister** [comment]
Interesting. How does this happen?

**Comment by wesleywiser** [comment]
([Related](https://rust-lang.zulipchat.com/#narrow/stream/186049-t-compiler.2Fwg-polonius/topic/profiling/near/166400330))

I guess this issue can probably be closed?

**Comment by michaelwoerister** [comment]
Ah yes, that's an obviously wrong usage of the API.

**Comment by lokalmatador** [comment]
Oh snap. Sorry, my bad. Should check my copy pasting better...anyways, thanks a lot for taking the time.
